// <auto-generated />
using APIazureserver.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIazureserver.Migrations
{
    [DbContext(typeof(ContactsContext))]
    [Migration("20220222125839_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIazureserver.Models.Contacts", b =>
                {
                    b.Property<string>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirtsName");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("dni");

                    b.HasKey("Identificador");

                    b.ToTable("ContactSet");
                });
#pragma warning restore 612, 618
        }
    }
}
